### ISSUE TITLE
debugging causes empty documents

### ISSUE THREAD

**Issue by ropoman** [ralfstuckert/mtom-sample#1]
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE works fine, but when I set
logging.level.org.springframework.ws=TRACE I receive empty documents.

**Comment by ralfstuckert** [comment]
Sorry pal, this stuff is two years old using ancient spring versions. I used it for documentation when I was using MTOM in a customer project, but I am no longer into it.

**Comment by ropoman** [comment]
No problem, I am just documenting my problems. This seems to be a spring bug
