### ISSUE TITLE
Missing xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0"

### ISSUE THREAD

**Issue by ropoman** [ralfstuckert/mtom-sample#2]
When I view http://localhost:9090/ws/documents.wsdl the <wsdl:definitions> is missing xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0". Why?

**Comment by ralfstuckert** [comment]
???
```
<wsdl:definitions ...
   <wsdl:types...
      <xs:schema xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" jaxb:version="2.0" targetNamespace="https://github.com/ralfstuckert/mtom">
```

**Comment by ropoman** [comment]
Yes, the jaxb:version is on xs:schema, but when I modify the schema on the mtom-server, then copy the wsdl to the mtom-client, it also needs the jaxb:version on wsdl:definitions. I just manually copy the two attributes

**Comment by ropoman** [comment]
and more thing: Danke! Schönes Beispiel. Hat mir viel Zeit gespart :)

**Comment by ralfstuckert** [comment]
:-)
